
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaxnxcpxhbsfwccsdpgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheG54Y3B4aGJzZndjY3NkcGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzMyMzIsImV4cCI6MjA2MjYwOTIzMn0.VOTLpxtlFrhDQXcdCPYYXGMQSqhw_69PukS5QcS8qeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    enabled: true
  }
});
